Quiron.LojaVirtual.Web/Models/Paginacao.cs
using System;

namespace Quiron.LojaVirtual.Web.Models
{
    public class Paginacao
    {
        public Int32 ItensTotal { get; set; }
        public Int32 ItensPorPagina { get; set; }
        public Int32 PaginaAtual { get; set; }
        public Int32 PaginaTotal { get { return (Int32)Math.Ceiling((decimal)ItensTotal/ItensPorPagina); } }
    }
}

Quiron.LojaVirtual.Web/Models/ProdutosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Quiron.LojaVirtual.Dominio.Entidade;

namespace Quiron.LojaVirtual.Web.Models
{
    public class ProdutosViewModel
    {
        public IEnumerable<Produto> Produtos { get; set; }

        public Paginacao Paginacao { get; set; }

        public String CategoriaAtual { get; set; }
    }
}

Quiron.LojaVirtual.Web/Controllers/CategoriaController.cs
using Quiron.LojaVirtual.Dominio.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class CategoriaController : Controller
    {
        private ProdutosRepositorio _repositorio;
        //
        // GET: /Categoria/
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Menu(string categoria = null)
        {
            _repositorio = new ProdutosRepositorio();

            ViewBag.CategoriaSelecionada = categoria;

            IEnumerable<string> categorias = _repositorio.GetProdutos.Select(p => p.Categoria).Distinct();
            
            return PartialView(categorias);
        }
	}
}

Quiron.LojaVirtual.Web/Controllers/ProdutoController.cs
using Quiron.LojaVirtual.Dominio.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private ProdutosRepositorio _repositorio;
        //
        // GET: /Produto/
        public ActionResult Index()
        {
            _repositorio = new ProdutosRepositorio();
            var produtos = _repositorio.GetProdutos().Take(10);

            return View();
        }
	}
}

Quiron.LojaVirtual.Web/Controllers/VitrineController.cs
using Quiron.LojaVirtual.Dominio.Repositorio;
using Quiron.LojaVirtual.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class VitrineController : Controller
    {
        private ProdutosRepositorio _repositorio;
        private int ProdutosPorPagina = 8;
        //
        // GET: /Vitrine/
        public ViewResult ListaProdutos(string categoria, int pagina = 1)
        {
            _repositorio = new ProdutosRepositorio();

            var viewModel = new ProdutosViewModel
            {
                Produtos = _repositorio.GetProdutos.OrderBy(p => p.Descricao)
                .Where(p => categoria == null || p.Categoria == categoria)
                .Skip((pagina - 1) * ProdutosPorPagina).Take(ProdutosPorPagina),
                Paginacao = new Paginacao
                {
                    PaginaAtual = pagina,
                    ItensPorPagina = ProdutosPorPagina,
                    ItensTotal = categoria == null ? _repositorio.GetProdutos.Count() : _repositorio.GetProdutos.Where(p => p.Categoria == categoria).Count()
                },
                CategoriaAtual = categoria
            };

            return View(viewModel);
        }
    }
}

Quiron.LojaVirtual.Web/Views/Categoria/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Todos os produtos", "ListaProdutos", "Vitrine", null, new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
    {
        controller = "Vitrine",
        action = "ListaProdutos",
        categoria = link,
        pagina = 1
    }, new 
    {
        @class = "btn btn-block btn-default btn-lg"
        + (link == ViewBag.CategoriaSelecionada ? " btn-primary" : "")
    })
}

Quiron.LojaVirtual.Web/Views/Produto/Index.cshtml
@model IEnumerable<Quiron.LojaVirtual.Dominio.Entidade.Produto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NomeProduto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NomeProduto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProdutoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProdutoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProdutoId })
        </td>
    </tr>
}

</table>

Quiron.LojaVirtual.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiron loja virtual</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" type="text/css">
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>

    <div class="nav navbar-inverse" role="navigation">
        <a href="#" class="navbar-brand">Quiron Loja Virtual - Seu esporte é aqui.</a>
    </div>



    <div class="row panel">

        <div id="categorias" class="col-xs-3">
            @Html.Action("Menu", "Categoria")
        </div>

        <div id="categorias" class="col-xs-7">
            @RenderBody()
        </div>

    </div>



    @*<div class="container body-content">

            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>*@

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Quiron.LojaVirtual.Web/Views/Shared/_ProdutoDetalhes.cshtml
@model Quiron.LojaVirtual.Dominio.Entidade.Produto

<div class="well">
    <h3><strong>@Model.Nome</strong></h3>

    <h3><span class="pull-right label label-primary">@Model.Preco.ToString("c")</span></h3>

    <h3><span class="lead">@Model.Descricao</span></h3>
</div>

Quiron.LojaVirtual.Web/Views/Vitrine/ListaProdutos.cshtml
@model Quiron.LojaVirtual.Web.Models.ProdutosViewModel
@using Quiron.LojaVirtual.Web.HtmlHelpers

@foreach (var item in Model.Produtos)
{
   @Html.Partial("_ProdutoDetalhes", item)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.Paginacao, x => Url.Action("ListaProdutos", new { pagina = x, categoria = Model.CategoriaAtual }))
</div>